const CACHE_NAME = 'prague-beer-zoo-v3';
const ASSETS_TO_CACHE = [
  './',
  './index.html',
  './manifest.json',
  './logo.svg',
  './logo192.png',
  './logo512.png'
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      console.log('[Service Worker] Pre-caching offline app shell');
      return cache.addAll(ASSETS_TO_CACHE);
    })
  );
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((allCacheNames) => {
      return Promise.all(
        allCacheNames.map((cache) => {
          if (cache !== CACHE_NAME) {
            console.log('[Service Worker] Removing old cache:', cache);
            return caches.delete(cache);
          }
        })
      );
    })
  );
  self.clients.claim();
});

/**
 * Network-First strategy for HTML/Document navigation requests.
 * This ensures the user always gets the latest index.html (and latest JS/CSS hashes) when online.
 */
function networkFirst(request) {
  return fetch(request)
    .then((networkResponse) => {
      if (networkResponse && networkResponse.status === 200) {
        const cacheCopy = networkResponse.clone();
        caches.open(CACHE_NAME).then((cache) => {
          cache.put(request, cacheCopy);
        });
      }
      return networkResponse;
    })
    .catch(() => {
      // Offline fallback: try to serve the exact request from cache,
      // fallback to './index.html' or './' if not found.
      return caches.match(request).then((cachedResponse) => {
        if (cachedResponse) return cachedResponse;
        return caches.match('./index.html').then((indexResponse) => {
          if (indexResponse) return indexResponse;
          return caches.match('./');
        });
      });
    });
}

self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);

  // We only intercept GET requests from the same origin
  if (event.request.method !== 'GET' || url.origin !== self.location.origin) {
    return;
  }

  // Detect HTML/document requests
  const isHtml = 
    event.request.mode === 'navigate' || 
    url.pathname.endsWith('/') || 
    url.pathname.endsWith('index.html');

  if (isHtml) {
    event.respondWith(networkFirst(event.request));
  } else {
    // Check if it's a hashed asset generated by Vite (e.g. index-XXXX.js)
    const isHashedAsset = url.pathname.includes('/assets/');

    if (isHashedAsset) {
      // Hashed assets are completely immutable. Cache-First is perfect.
      event.respondWith(
        caches.match(event.request).then((cachedResponse) => {
          if (cachedResponse) {
            return cachedResponse;
          }
          return fetch(event.request).then((networkResponse) => {
            if (networkResponse && networkResponse.status === 200) {
              const cacheCopy = networkResponse.clone();
              caches.open(CACHE_NAME).then((cache) => {
                cache.put(event.request, cacheCopy);
              });
            }
            return networkResponse;
          });
        })
      );
    } else {
      // Stale-While-Revalidate for other static assets (logos, manifest etc.)
      event.respondWith(
        caches.match(event.request).then((cachedResponse) => {
          const fetchPromise = fetch(event.request)
            .then((networkResponse) => {
              if (networkResponse && networkResponse.status === 200) {
                const cacheCopy = networkResponse.clone();
                caches.open(CACHE_NAME).then((cache) => {
                  cache.put(event.request, cacheCopy);
                });
              }
              return networkResponse;
            })
            .catch(() => {
              // Ignore network failures gracefully when offline
            });

          return cachedResponse || fetchPromise;
        })
      );
    }
  }
});
